apiVersion: v1
kind: Service
metadata:
  name: api-vpbank-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    name: port80
    targetPort: 80
    protocol: TCP
    nodePort: 30629
  selector:
    app: apivpbankmutosi
