apiVersion: v1
kind: Service
metadata:
  name: frontendmutositest-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30999
  selector:
    app: frontendmutositest
